kind: pipeline
type: docker # exec, ssh ,kubernetes
name: default

platform:
  arch: amd64

steps:
  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go env
      - go version
      - make build
      - ls 
      - bin/runner -v

  - name: scp files
    image: appleboy/drone-scp
    settings:
      host: 
        - www.asppj.top
      port: 22
      key:
        source: privateKey
        target: scp_key
      target: /root/deploy-prometheus/prometheus
      source: bin/runner

  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host:
        -  www.asppj.top
      port: 22
      key:
        source: privateKey
        target: ssh_key
      script:
        - echo hello
        - echo world
        - uname -a
        - pwd
        - ls
