kind: pipeline
type: docker # exec, ssh ,kubernetes
name: default

platform:
  arch: amd64

steps:
  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go env
      - go version
      - make build
      - ls 
      - bin/runner -v



  - name: scp files
    image: appleboy/drone-scp
    settings:
      host: 
        - 39.100.86.233
      username: root
      port: 22
      key: 
        from_secret: private_ssh
      // password: 
      //   from_secret: ali_password
      target: /root/deploy-droneDeploy/droneDeploy
      source: 
        - bin/runner
        - scripts/deploy.sh

  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host:
        -  www.asppj.top
      port: 22
      key: 
        from_secret: private_ssh
      script:
        - echo hello
        - echo world
        - uname -a
        - pwd
        - ls
        - ~/deploy-droneDeploy/droneDeploy/bin/runner -v


  - name: publish
    image: plugins/github-release
    settings:
      api_key: 
        from_secret: github_token
      files: bin/

